[package]
name = "assignment_code"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
rand = "0.9.0"
libc = "0.2"
shared_memory = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0", features = ["serde"] }
