[package]
name = "assignment_code"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
rand = "0.9.0"
libc = "0.2"
winapi = "0.3.9"
ipc-channel = "0.19.0"
